name: shule_yetu_flutter_ui
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/previews/
    - assets/modules/
    - assets/images/modules/
